<script type="text/javascript">
 //<![CDATA[
 function fireTestEvent() {
   new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
     parameters: {
       apiKey: $('dev_Bugsnag_Notifier_apiKey').value,
       severities: $('dev_Bugsnag_Notifier_severities').value,
       filterFiels: $('dev_Bugsnag_Notifier_filterFields').value
     },
     onSuccess: function(transport) {
       alert('Sent notification. Visit https://bugsnag.com/ to see it in your dashboard');
     },
     onFailure: function(transport) {
       alert("Couldn't send a notification. Double check your API key");
     }
   });
 }
 //]]>
</script>

<?php echo $this->getButtonHtml() ?>
